# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "localities", :force => true do |t|
    t.column "postcode", :string, :limit => 4, :default => "", :null => false
    t.column "suburb",   :string,              :default => "", :null => false
    t.column "state",    :string, :limit => 3, :default => "", :null => false
    t.column "comments", :string,              :default => "", :null => false
  end

  add_index "localities", ["postcode"], :name => "index_localities_on_postcode"
  add_index "localities", ["suburb"], :name => "index_localities_on_suburb"
  add_index "localities", ["state"], :name => "index_localities_on_state"

end
